# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UBC Stat406 2022W
email: daniel@stat.ubc.ca
author: Daniel J. McDonald
author-url: https://dajmcdon.github.io/
description: > # this means to ignore newlines until "baseurl:"
  UBC Stat 406 - Elements of Statistical Learning Winter Term 1, 2020
# baseurl: "/stat-406" # the subpath of your site, e.g.
url: "https://ubc-stat.github.io/stat-406"
lang: en # language can also be set on a per page basis. Primary use right now is only for <html lang="">

# Build settings
markdown: kramdown
remote_theme: dajmcdon/minimal-course
permalink: /:title/
navbar: dark          # other options: light/dark
theme-primary: "#6f42c1"
theme-secondary: "#fd7e14"
navbar-fixed-top: true # if true, also check _sass/bootstrap4-cdn.scss padding top
logo_path: /assets/img/chart-bar-white.svg # optional

google_fonts: 'Cormorant Garamond'

use-license: true

navigation:
  - title: Syllabus
    url: /syllabus/
  - title: Schedule
    url: /schedule/
  - title: Worksheets
    url: https://ubc-stat.github.io/stat-406-worksheets/
  - title: Project
    url: /project/
  - title: Computing
    url: /computing/
  - title: FAQ
    url: /faq/
  - title: Github
    url: https://learning.github.ubc.ca/STAT-406-101-2021W/
    icon: "fab fa-github"
