---
title: "Welcome to Stat 406"
subtitle: "Methods for Statistical Learning"
toc: false
css: assets/index.css
about: trestles
image: assets/img/smooths.svg
---


::: {.align-center}

::: {.hero-buttons}
[Jump to Schedule](lectures/index.qmd){.btn-action-primary .btn-action .btn .btn-lg role="button"}
[Syllabus](syllabus.qmd){.btn-action-secondary .btn-action .btn .btn-lg role="button"}
::: 

:::

At the end of the course, you will be able to: 

* Assess the prediction properties of the supervised learning methods covered in class;
* Correctly use regularization to improve predictions from linear models, and also to identify important explanatory variables; 
* Explain the practical
difference between predictions obtained with parametric and non-parametric methods, and decide in specific applications which approach should be used; 
* Select and construct appropriate ensembles to obtain improved predictions in different contexts; 
* Use and interpret principal components and other dimension reduction techniques;
* Employ reasonable coding practices and understand basic R syntax and function.
* Write reports and use proper version control; engage with standard software.
