---
title: "{{< fa brands r-project >}} Computing"
---

In order to participate in this class, we will require the use of R, and encourage
the use of RStudio. Both are free, and you likely already have both. 

You also need Git, Github and Slack.

Below are instructions for installation. These are edited and simplified from the [DSCI 310 Setup Instructions](https://ubc-dsci.github.io/dsci-310-student/computer-setup.html). If you took DSCI 310 last year, you may be good to go, with the exception of the [R package](https://ubc-stat.github.io/stat-406-rpackage/).

## Laptop requirements

 - Runs one of the following operating systems: Ubuntu 20.04, macOS (version 11.4.x or higher), Windows 10 (version 2004, 20H2, 21H1 or higher).
    - When installing Ubuntu, checking the box "Install third party..." will (among other things) install proprietary drivers, which can be helpful for wifi and graphics cards.
- Can connect to networks via a wireless connection for on campus work
- Has at least 30 GB disk space available
- Has at least 4 GB of RAM
- Uses a 64-bit CPU
- Is at most 6 years old (4 years old or newer is recommended)
- Uses English as the default language. Using other languages is possible, but we have found that it often causes problems in the homework. We've done our best to fix them, but we may ask you to change it if you are having trouble.
- Student user has full administrative access to the computer.

## Software installation instructions

Please click the appropriate link below to view the installation instructions for your operating system:

- [macOS x86](mac_x86.qmd) or [macOS arm](mac_arm.qmd) 
- [Ubuntu](ubuntu.qmd)
- [Windows](windows.qmd)


